include:
- file: helmfile-infra/infra-pipeline.gitlab-ci.yml
  project: devops/tools/ci
  ref: $CI_LIBRARY_REF_NAME

variables:
  CI_LIBRARY_REF_NAME: $CI_LIBRARY_REF_NAME
  JOB_RUNNER_TAG_DEPLOYMENT_PRODUCTION: gtl-k8s-dev
