include:
- file: helmfile-jobs.yaml
  project: devops/tools/ci

variables:
  JOB_RUNNER_TAG_DEPLOYMENT: gtl-k8s-dev

deploy upstream:
  extends: .deploy helmfile job
  rules:
  - if: >-
      $CI_PIPELINE_SOURCE == 'pipeline'
      && $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  tags:
  - $JOB_RUNNER_TAG_DEPLOYMENT
  environment:
    auto_stop_in: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    name: $UPSTREAM_ENVIRONMENT_NAME
    on_stop: remove upstream

remove upstream:
  extends: .destroy helmfile job
  needs:
  - job: deploy upstream
  rules: !reference [deploy upstream, rules]
  tags: !reference [deploy upstream, tags]
  environment:
    name: !reference [deploy upstream, environment, name]
