include:
- file: helmfile-infra/service-pipeline.gitlab-ci.yml
  project: devops/tools/ci

variables:
  CONTAINER_IMAGE_BASE_NAME: ikva-service
  HELM_CHART_PROJECT_PATH: devops/samples/ikva/ikva-helmchart
  INFRA_PROJECT_PATH: devops/samples/ikva/ikva-infra

build container image:
  extends: .build container image job
  rules:
  - !reference [.build container image job, rules]
  - changes:
    - Dockerfile
  tags:
  - gtl-k8s-dev
  variables:
    CONTAINER_IMAGE_BUILD_ARGS: |-
      DOCKER_REGISTRY=${ARTIFACTORY_URL}/dkr

merge request:
  stage: .pre
  image: ${ARTIFACTORY_URL}/dkr/devops-tools-plain-job-runner
  script:
  - env
  - echo ${TOKEN_NAME:=$(echo ${GITLAB_USER_LOGIN}_COMMIT_TOKEN | tr '[:lower:]' '[:upper:]')}
  - echo ${PRIVATE_TOKEN:=$(echo ${!TOKEN_NAME})}
  - >-
    curl
    --form "token=${CI_JOB_TOKEN}"
    --silent
    ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests?state=opened
