include:
- file: helmfile-infra/service-pipeline.gitlab-ci.yml
  project: devops/tools/ci
  ref: $CI_LIBRARY_REF_NAME

variables:
  CONTAINER_IMAGE_BASE_NAME: ikva-service
  HELM_CHART_PROJECT_PATH: devops/samples/ikva/ikva-helmchart
  INFRA_PROJECT_PATH: devops/samples/ikva/ikva-infra
  INFRA_SELECT_DEPLOYMENT: ikva

build container image:
  rules:
  - !reference [.build container image, rules]
  - changes:
    - Dockerfile
  tags:
  - gtl-k8s-dev
  variables:
    CONTAINER_IMAGE_BUILD_ARGS: |-
      DOCKER_REGISTRY=${ARTIFACTORY_URL}/dkr
