include:
- file: container-helmfile-jobs.gitlab-ci.yml
  project: devops/tools/ci

workflow:
  rules:
  - !reference [.container helmfile jobs, workflow rules]
  - when: always

variables:
  CONTAINER_IMAGE_BASE_NAME: ikva-service
  HELM_CHART_PROJECT_PATH: devops/samples/ikva/ikva-helmchart
  INFRA_PROJECT_PATH: devops/samples/ikva/ikva-infra
  JIRA_TICKET:
    options:
    - DEPX-000
    - DEPX-001
    value: DEPX-000

build container image:
  extends: .build container image job
  rules:
  - if: $PIPELINE_ACTION && $PIPELINE_ACTION == $PIPELINE_ACTION_DEPLOY_RELEASE_TO_PRODUCTION
    when: never
  - changes:
    - Dockerfile
  variables:
    CONTAINER_IMAGE_BUILD_ARGS: |-
      DOCKER_REGISTRY=${ARTIFACTORY_URL}/dkr

promote container image:
  extends: .promote release container image job

deploy environment:
  extends: .trigger helm chart project job
  variables:
    HELM_CHART_APP_VERSION: $CONTAINER_IMAGE_TAG
