include:
- file: helmfile-infra/service-pipeline.gitlab-ci.yml
  project: devops/tools/ci

variables:
  CONTAINER_IMAGE_BASE_NAME: ikva-service
  HELM_CHART_PROJECT_PATH: devops/samples/ikva/ikva-helmchart
  INFRA_PROJECT_PATH: devops/samples/ikva/ikva-infra

build container image:
  extends: .build container image job
  rules:
  - !reference [.build container image job, rules]
  - changes:
    - Dockerfile
  tags:
  - gtl-k8s-dev
  variables:
    CONTAINER_IMAGE_BUILD_ARGS: |-
      DOCKER_REGISTRY=${ARTIFACTORY_URL}/dkr

publish release:
  stage: .pre
  trigger:
    include:
    - file: gitlab/release-pipeline.gitlab-ci.yml
      project: devops/tools/ci
