bases:
- git::https://user:{{ env "GITLAB_TOKEN" }}@gitlab.gtl.net/devops/tools/ci.git@helmfile/templates.yaml?ref={{ env "CI_LIBRARY_REF_NAME" | default "main" }}

repositories:
- name: viapath
  url: https://artifactory.gtl.net/artifactory/helm

templates:
  ikva:
    chart: viapath/ikva-service
    inherit:
    - template: base
    timeout: 120
    version: {{ env "IKVA_CHART_VERSION" | quote }}
    wait: true
